image: canvadev/ci-docker-node-yarn-chrome-xvfb

stages:
  - packages
  - lint
  - test
  - build
  - deploy

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

packages:
  stage: packages
  script: "yarn install"

lint:
  stage: lint
  script: "yarn run lint"

test:
  stage: test
  script:
    - yarn run test
  coverage: '/Statements\s*:\s*([^%]+)/'

build:
  only:
    - develop
  stage: build
  tags: 
    - open360-shell
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN git:5000
  script:
    - yarn build
    - docker build --tag=git:5000/open360/frontend:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID} --file=".docker/bw-assessment-ui.prod.dockerfile" .
    - docker push git:5000/open360/frontend:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}

deploy:
  only:
    - develop
  stage: deploy
  tags: 
    - open360-shell
  environment:
    name: Development
    url: http://netpoint-dc.com
  before_script: 
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN git:5000
  script:
    - docker rm -f public-bw-assessment-ui || true
    - docker run -d --restart=always -p  80:80 --name public-bw-assessment-ui \
                 git:5000/open360/frontend:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID} \
                 -v /src/deploy-configs/dev.json:/dist/prod/assets/config.json
