language: node_js
node_js: 12.14.0
services: docker
cache:
  npm: true
  yarn: true
addons:
  chrome: stable
install:
  - yarn install
script:
  - yarn run lint
  - yarn run test
after_success:
  - yarn coveralls
before_deploy:
  - yarn build.prod
  - docker build --tag="$DOCKER_REPOSITORY:$([ "$TRAVIS_BRANCH" == "master" ] && echo "latest" || echo "$TRAVIS_BRANCH")" --file=".docker/bw-assessment-ui.prod.dockerfile" .
  - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script: docker push "$DOCKER_REPOSITORY_NAME:$([ "$TRAVIS_BRANCH" == "master" ] && echo "latest" || echo "$TRAVIS_BRANCH")"
  on:
    all_branches: true
    condition: $TRAVIS_PULL_REQUEST = false
